# Generated by Django 5.0.1 on 2024-04-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_user_productdetails_marchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='marchant',
            new_name='merchant',
        ),
    ]
