# Generated by Django 5.0.1 on 2024-04-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_marchant_productdetails_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myproteindetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Category', models.CharField(choices=[('category1', 'Category 1'), ('category2', 'Category 2')], max_length=100)),
                ('product_Name', models.CharField(max_length=225)),
                ('product_Description', models.CharField(max_length=1000)),
                ('product_image', models.FileField(upload_to='proteinpowder_image')),
            ],
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_Category',
            field=models.CharField(choices=[('full body workout', 'full body workout'), ('Yoga Flow with an Exercise Ball', 'Yoga Flow with an Exercise Ball'), ('Bed Exercises', 'Bed Exercises'), ('Home Workout', 'Home Workout'), ('Yoga in Bed', 'Yoga in Bed')], max_length=255),
        ),
    ]
