# Generated by Django 5.0.1 on 2024-05-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_myproteindetails_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproteindetails',
            name='product_price',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myproteindetails',
            name='product_Category',
            field=models.CharField(choices=[('full body workout', 'full body workout'), ('full body ', 'full body ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='myproteindetails',
            name='product_image',
            field=models.FileField(upload_to='product_image'),
        ),
    ]
