# Generated by Django 5.0.1 on 2024-05-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_myproteindetails_product_category_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalprice',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='myproteindetails',
            name='product_price',
            field=models.FloatField(max_length=225),
        ),
    ]
